"""Type stubs for the compiled `_lutufi` native extension module.

This module is implemented in Rust (PyO3) and has no Python source; the
declarations below describe its public surface for type checkers.

Most of these classes are low-level wrappers used internally by the
`lutufi` Python package (see `lutufi.models`, `lutufi.inference`, and
`lutufi.learning`). End users should generally prefer the higher-level
wrappers in those modules.
"""

from typing import Any, Dict, List, Optional, Tuple

__version__: str

# ─── Variables and Domains ─────────────────────────────────────────────────

class Domain:
    """A variable's domain (the set of values it can take)."""

    @staticmethod
    def discrete(states: List[str]) -> "Domain": ...
    @staticmethod
    def binary() -> "Domain": ...
    @staticmethod
    def continuous(
        lower: Optional[float] = ..., upper: Optional[float] = ...
    ) -> "Domain": ...
    @property
    def size(self) -> Optional[int]: ...
    @property
    def is_discrete(self) -> bool: ...
    @property
    def states(self) -> Optional[List[str]]: ...
    def contains(self, value: str) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Variable:
    """A random variable with a name and a domain."""

    def __init__(self, name: str, domain: List[str]) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def domain(self) -> Domain: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

# ─── Validation ─────────────────────────────────────────────────────────────

class ValidationResult:
    """The result of validating a model for inference."""

    is_valid: bool
    errors: List[str]
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

class QueryResult:
    """Reserved for future use by the native extension."""
    ...

# ─── Bayesian Network ───────────────────────────────────────────────────────

class _RustBayesianNetwork:
    """Native handle for a Bayesian network."""

    def __init__(self) -> None: ...
    def add_variable(self, name: str, domain: List[str]) -> None: ...
    def add_edge(self, from_name: str, to_name: str) -> None: ...
    def remove_edge(self, from_name: str, to_name: str) -> None: ...
    def set_cpd(
        self, variable_name: str, values: Any
    ) -> None: ...
    def get_cpd(self, variable_name: str) -> Dict[str, List[float]]: ...
    def nodes(self) -> List[str]: ...
    def edges(self) -> List[Tuple[str, str]]: ...
    def topological_order(self) -> List[str]: ...
    def markov_blanket(self, variable_name: str) -> List[str]: ...
    def validate(self) -> ValidationResult: ...
    def is_valid(self) -> bool: ...
    def mark_as_causal(self) -> None: ...
    def d_separated(self, a: str, b: str, given: List[str]) -> bool: ...
    def get_states(self, variable_name: str) -> List[str]: ...
    def is_causal(self) -> bool: ...
    def do_operator(self, intervention: Dict[str, str]) -> "_RustBayesianNetwork": ...
    def causal_query(
        self, targets: List[str], interventions: Dict[str, str]
    ) -> Dict[str, List[float]]: ...
    def counterfactual(
        self, observed: Dict[str, str], intervention: Dict[str, str], query: List[str]
    ) -> Dict[str, List[float]]: ...
    def probability_of_necessity(
        self, outcome: str, outcome_value: str, treatment: str,
        treatment_value: str, reference_value: str,
    ) -> float: ...
    def probability_of_sufficiency(
        self, outcome: str, outcome_value: str, treatment: str,
        treatment_value: str, reference_value: str,
    ) -> float: ...
    def identify(
        self, targets: List[str], interventions: List[str]
    ) -> Tuple[bool, str]: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> "_RustBayesianNetwork": ...
    def to_lmf_json(self) -> str: ...
    @staticmethod
    def from_lmf_json(json: str) -> "_RustBayesianNetwork": ...
    def __copy__(self) -> "_RustBayesianNetwork": ...
    def __deepcopy__(self, memo: Any) -> "_RustBayesianNetwork": ...

# ─── Markov Random Field ────────────────────────────────────────────────────

class _RustMarkovRandomField:
    """Native handle for a Markov random field."""

    def __init__(self) -> None: ...
    def add_variable(self, name: str, domain: List[str]) -> None: ...
    def add_edge(self, name1: str, name2: str) -> None: ...
    def nodes(self) -> List[str]: ...
    def edges(self) -> List[Tuple[str, str]]: ...

# ─── Dynamic Bayesian Network ───────────────────────────────────────────────

class _RustDynamicBayesianNetwork:
    """Native handle for a dynamic Bayesian network."""

    def __init__(self) -> None: ...
    def add_variable(self, name: str, domain: List[str]) -> None: ...
    def add_intraslice_edge(self, from_name: str, to_name: str) -> None: ...
    def add_interslice_edge(self, from_name: str, to_name: str) -> None: ...

# ─── Inference Engines ──────────────────────────────────────────────────────

class _RustVariableEliminationEngine:
    """Exact inference via variable elimination."""

    def __init__(self) -> None: ...
    def query(
        self,
        model: _RustBayesianNetwork,
        variables: List[str],
        evidence: Dict[str, str],
        heuristic: Optional[str] = ...,
    ) -> Dict[str, Any]: ...
    def query_map(
        self,
        model: _RustBayesianNetwork,
        variables: List[str],
        evidence: Dict[str, str],
        heuristic: Optional[str] = ...,
        mode: str = ...,
    ) -> Dict[str, Any]: ...

class _RustJunctionTreeEngine:
    """Exact inference via junction tree propagation."""

    def __init__(self, model: _RustBayesianNetwork) -> None: ...
    def treewidth(self) -> int: ...
    def query(
        self,
        variables: List[str],
        evidence: Optional[Dict[str, str]] = ...,
    ) -> Dict[str, Any]: ...

class _RustLBPEngine:
    """Approximate inference via loopy belief propagation."""

    def __init__(self) -> None: ...
    def query(
        self,
        model: _RustBayesianNetwork,
        variables: List[str],
        evidence: Dict[str, str],
        max_iterations: int = ...,
        tolerance: float = ...,
        damping: float = ...,
    ) -> Dict[str, Any]: ...

class _RustMCMCEngine:
    """Approximate inference via Gibbs/MCMC sampling."""

    def __init__(self) -> None: ...
    def query(
        self,
        model: _RustBayesianNetwork,
        variables: List[str],
        evidence: Dict[str, str],
        n_samples: int = ...,
        burn_in: int = ...,
    ) -> Dict[str, Any]: ...

class _RustVariationalEngine:
    """Approximate inference via mean-field variational inference."""

    def __init__(self) -> None: ...
    def query(
        self,
        model: _RustBayesianNetwork,
        variables: List[str],
        evidence: Dict[str, str],
        max_iterations: int = ...,
        tolerance: float = ...,
    ) -> Dict[str, Any]: ...

# ─── Learning ────────────────────────────────────────────────────────────────

class _RustParameterEstimator:
    """Learns CPT parameters from data."""

    def __init__(
        self, method: str = ..., alpha: float = ..., max_iterations: int = ...
    ) -> None: ...
    def fit(
        self,
        model: _RustBayesianNetwork,
        data: List[Dict[str, str]],
    ) -> None: ...

class _RustStructureLearner:
    """Learns graph structure from data."""

    def __init__(self) -> None: ...
    def learn_structure(
        self, data: List[Dict[str, str]], method: str = ...
    ) -> _RustBayesianNetwork: ...
